# Amalgam Package Generation Manifest for nickel-pkgs repository
# This file defines all packages to be generated and maintained in nickel-pkgs
# All URLs have been verified to contain actual CRD files

[config]
# Output directory for all generated packages
output_base = "pkgs"
# Enable package mode by default (generate submittable packages)
package_mode = true
# Base package ID for dependencies
base_package_id = "github:seryl/nickel-pkgs/pkgs"

# Kubernetes Core Types - Foundation for all other packages
[[packages]]
name = "k8s-io"
type = "k8s-core"
version = "v1.33.4"
output = "k8s_io"
description = "Kubernetes core type definitions for Nickel"
keywords = ["kubernetes", "k8s", "types", "api", "core"]

# ArgoCD - GitOps Continuous Delivery
[[packages]]
name = "argocd"
type = "url"
url = "https://github.com/argoproj/argo-cd/tree/v3.1.1/manifests/crds"
git_ref = "v3.1.1"
version = "3.1.1"
output = "argocd"
description = "ArgoCD CRD type definitions for GitOps"
keywords = ["gitops", "continuous-delivery", "kubernetes", "argo", "deployment"]
dependencies = { k8s_io = "1.33.4" }

# cert-manager - Certificate Management
[[packages]]
name = "cert-manager"
type = "url"
url = "https://github.com/cert-manager/cert-manager/tree/v1.18.2/deploy/crds"
git_ref = "v1.18.2"
version = "1.18.2"
output = "cert-manager"
description = "cert-manager CRD type definitions for Nickel"
keywords = ["certificates", "tls", "security", "kubernetes", "acme"]
dependencies = { k8s_io = "1.33.4" }

# CrossPlane - Infrastructure as Code
[[packages]]
name = "crossplane"
type = "url"
url = "https://github.com/crossplane/crossplane/tree/v2.0.2/cluster/crds"
git_ref = "v2.0.2"
version = "2.0.2"
output = "crossplane"
description = "Crossplane CRD type definitions for Nickel"
keywords = ["crossplane", "kubernetes", "infrastructure", "gitops", "platform"]
dependencies = { k8s_io = "1.33.4" }

# FluxCD Kustomize Controller
[[packages]]
name = "fluxcd-kustomize"
type = "url"
url = "https://github.com/fluxcd/kustomize-controller/tree/v1.6.1/config/crd/bases"
git_ref = "v1.6.1"
version = "1.6.1"
output = "fluxcd/kustomize"
description = "FluxCD Kustomize Controller CRD type definitions"
keywords = ["gitops", "fluxcd", "kustomize", "kubernetes", "configuration"]
dependencies = { k8s_io = "1.33.4" }

# FluxCD Source Controller
[[packages]]
name = "fluxcd-source"
type = "url"
url = "https://github.com/fluxcd/source-controller/tree/v1.6.2/config/crd/bases"
git_ref = "v1.6.2"
version = "1.6.2"
output = "fluxcd/source"
description = "FluxCD Source Controller CRD type definitions"
keywords = ["gitops", "fluxcd", "continuous-delivery", "kubernetes", "source"]
dependencies = { k8s_io = "1.33.4" }

# KEDA - Event-driven Autoscaling
[[packages]]
name = "keda"
type = "url"
url = "https://github.com/kedacore/keda/tree/v2.17.2/config/crd/bases"
git_ref = "v2.17.2"
version = "2.17.2"
output = "keda"
description = "KEDA autoscaling CRD type definitions"
keywords = ["autoscaling", "keda", "events", "kubernetes", "scaling"]
dependencies = { k8s_io = "1.33.4" }

# Knative - Serverless
[[packages]]
name = "knative"
type = "url"
url = "https://github.com/knative/operator/tree/knative-v1.17.8/config/crd/bases"
git_ref = "knative-v1.17.8"
version = "1.17.8"
output = "knative"
description = "Knative Operator CRD type definitions"
keywords = ["serverless", "knative", "functions", "kubernetes", "scale-to-zero"]
dependencies = { k8s_io = "1.33.4" }

# Prometheus Operator - Monitoring
[[packages]]
name = "prometheus-operator"
type = "url"
url = "https://github.com/prometheus-operator/prometheus-operator/tree/v0.85.0/example/prometheus-operator-crd"
git_ref = "v0.85.0"  # Lock to specific version
version = "0.85.0"   # Package version
output = "prometheus"
description = "Prometheus Operator CRD type definitions"
keywords = ["prometheus", "monitoring", "observability", "kubernetes", "metrics"]
dependencies = { k8s_io = "1.33.4" }

# Tekton - CI/CD Pipelines
[[packages]]
name = "tekton"
type = "url"
url = "https://github.com/tektoncd/pipeline/tree/v1.3.1/config/300-crds"
git_ref = "v1.3.1"
version = "1.3.1"
output = "tekton"
description = "Tekton CI/CD pipeline CRD type definitions"
keywords = ["ci-cd", "pipelines", "tekton", "kubernetes", "automation"]
dependencies = { k8s_io = "1.33.4" }

# Note: The following packages were removed as they were marked as disabled
# due to requiring special handling for their CRD formats:
# - Traefik (non-standard CRD location/format)
# - Longhorn (single YAML file format)
# - Contour (single YAML file format)
# These can be added back once Amalgam supports their specific formats
