# Module: k8s.io.v1.grpcaction

{
  # GRPCAction specifies an action involving a GRPC service.
  GRPCAction = {
    port | Number | doc "Port number of the gRPC service. Number must be in the range 1 to 65535.",
    service | optional | String | doc m%"
Service is the name of the service to place in the gRPC HealthCheckRequest (see https://github.com/grpc/grpc/blob/master/doc/health-checking.md).

If this is not specified, the default behavior is defined by gRPC.
"%,
  },
}
